INSERT INTO atm(name, address,city)VALUES ('Halkbank-Bitola 2 ATM', 'Josif Josifovski Sveshtarot 1"', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Halkbank-Shirok sokak ATM', 'Shirok Sokak (Marshal Tito) b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Halkbank-Sport life ATM', 'Partizanska 94 lok.1', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Komercijalna Banka Partizanska-ATM', 'Partizanska b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Komercijalna Banka TC-ATM', 'Vasko Karangeleski 71', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Komercijalna Banka Teo Travel-ATM', 'Marshal Tito 60', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Komercijalna banka-Bitola', 'Nikola Tesla 18', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('NLB Banka-Bitola', 'Josif Hristovski b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('NLB Banka-Bitola', 'Vasko Karangeleski 3/37', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('NLB Banka-Bitola-Sud ATM', 'bul.1-vi Maj b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('NLB Banka-Sirok sokak', 'Shirok Sokak (Marshal Tito) 45', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('NLB Banka-Tineks', 'Zaharija Shumljanska (Prilepska) 5', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('ProCredit Bank-Bitola', 'Dobrivoje Radosavljevikj 10', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('ProCredit Bank-Stara Carshija', 'Stara Carsija', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('ProCredit Banka-Impuls Nova Bitola ATM', 'Vidan Janakievski 3', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Silk Road Bank - Bitola', 'Ignjat Atanasovski b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Sparkasse Bank-Bitola', '1-vi Maj 1', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD-Skopje-Bitola-Vero(Stopanska Banka AD-Skopje-Bitola)', 'Vasko Karangeleski 41', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD-Skopje-Bitola-Vero(Stopanska Banka AD-Skopje-Bitola)', 'Vasko Karangeleski 41', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka', 'Todor Skalovski 8', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD Bitola-ATM Bitola', 'Novachki pat, s.Novaci b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD Bitola-ATM Bitola', 'Zaharija Shumljanska (Prilepska) 44', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD Bitola-ATM Bitola', 's.Suvodol', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD Skopje ATM', 'Shirok Sokak (Marshal Tito) 16', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD-Skopje-ATM-Bitola (Stopanska banka AD-Skopje-ATM Bitola)', 'Partizanska b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD-Skopje-ATM-Bitola (Stopanska banka AD-Skopje-ATM Bitola)', 'Stolarska b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD-Skopje-ATM-Bitola (Stopanska banka AD-Skopje-ATM Bitola)', '4-ti Noemvri b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka AD-Skopje-ATM-Bitola (Stopanska banka AD-Skopje-ATM Bitola)', 'Filip Vtori Makedonski (Ivan Milutinovikj) 54', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka Bitola AD', 'Shirok Sokak (Marshal Tito) 16', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka Bitola AD', 'Dobrivoje Radosavljevikj 21', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska Banka Reonsko Pazariste AD Bitola-ATM', 'Vasko Karangeleski b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Stopanska banka Btiola AD', 'Partizanska b.b.', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('TTK Banka', 'Stolarska 1-g', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('TTK Banka', 'Zaharija Shumljanska (Prilepska) 42', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('TTK Banka-Ekspozitur Bitola PP', 'bul.1-vi Maj 204/4', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('TTK Banka-Bitola Nova Bitola', 'Vasko Karangeleski 41', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('TTK Banka-Filijala Bitola', 'Stolarska 7', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Uni Bank (Uni Banka) ATM', 'Filip Vtori Makedonski (Ivan Milutinovikj) 52', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Uni Banka-ATM', 'Vasko Karangelevski 31', 'Bitola');
INSERT INTO atm(name, address,city)VALUES ('Uni Banka-ATM ATM', 'Leninova 1', 'Bitola');
